FROM ruby:3.4.4

EXPOSE 4567
CMD ["/usr/bin/supervisord"]

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y supervisor=4.2.5-1 && apt-get install jq=1.6-2.1 -y
RUN mkdir -p /var/log/supervisor

RUN bundle config --global frozen 1 && bundle config set --local without 'dev'

COPY setup-go.sh setup-go.sh
RUN bash setup-go.sh

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
