wall:
  wrapped: 0
  standard: -5
hazard:
  wrapped: -550
  standard: -15
hazard_adjacent:
  wrapped: 0
  standard: -7
food:
  wrapped: 55
  standard: 15
food_hazard:
  wrapped: 0
  standard: 2
food_adjacent:
  wrapped: 20
  standard: 2
shared_neighbor:
  wrapped: 0
  standard: 0
shared_shorter_snake:
  wrapped: 45
  standard: 5
shared_longer_snake:
  wrapped: -80
  standard: -60
shared_same_length_snake:
  wrapped: -75
  standard: -10
empty:
  wrapped: 55
  standard: 8
snake_head:
  wrapped: -2
  standard: -2
snake_body:
  wrapped: -2
  standard: -2
snake_body_neighbor:
  wrapped: -20
  standard: -10
corner:
  wrapped: -1
  standard: -1
other_snake_head:
  wrapped: -2
  standard: -2
other_snake_body:
  wrapped: -20
  standard: -100
other_snake_head_neighbor:
  wrapped: 0
  standard: 0
body:
  wrapped: -100
  standard: -5
head:
  wrapped: -4
  standard: -4
tail:
  wrapped: 2
  standard: 2
my_tail:
  wrapped: 10
  standard: 80
my_tail_neighbor:
  wrapped: 30
  standard: 20
edge:
  wrapped: 0
  standard: -4
edge_adjacent:
  wrapped: 0
  standard: -1
head_neighbor:
  wrapped: 0
  standard: 0
three_head_neighbor:
  wrapped: -2
  standard: -2
shorter_snake_heads:
  wrapped: 4
  standard: 5
