name: Base Image build + push toGHCR - main branch
permissions:
  packages: write

on:
    push:
        branches:
            - main

    workflow_dispatch:

jobs:

  build-base-main:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v5

    - name: Build the base Docker image
      run: docker build . --file Dockerfile.base --tag ghcr.io/es-na-battlesnake/code-snake:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/es-na-battlesnake/code-snake:latest
