name: Dependabot Auto Approve

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto approve dependabot PRs
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prTitle = context.payload.pull_request.title;
            
            console.log(`Auto-approving dependabot PR #${prNumber}: ${prTitle}`);
            
            try {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                event: 'APPROVE',
                body: '🤖 Auto-approved by GitHub Actions for dependabot PR'
              });
              
              console.log(`✅ Successfully approved PR #${prNumber}`);
            } catch (error) {
              console.error(`Failed to approve PR: ${error.message}`);
            }