name: Go

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go' 

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.17

    - name: Test
      working-directory: ./snakes
      run: go test -v ./...
