name: New Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  comment:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      # Post a comment on newly opened PRs describing the deployment process and related PR steps to deploy
      - uses: actions/checkout@v4 
      - name: comment
        uses: GrantBirki/comment@v2.1.0
        with:
          file: .github/new_pull_request.md