name: Docker Image CI - Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag code-snek:$GITHUB_HEAD_REF
    - name: Run the Docker image
      run: docker run -d -p 4357:4357 code-snek:$GITHUB_HEAD_REF
    - name: Test app response
      run: curl -v http://localhost:4357/
