name: Docker Image CI - Pull Request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag code-snek:pr
    - name: Run the Docker image
      run: docker run -d -p 4567:4567 --name=code-snek code-snek:pr
    - name: Test app response
      run: curl -v http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' code-snek):4567/
