# github action that just checks for the files changed in a PR
name: "test-changed-files"

on:
  workflow_dispatch:
  # run on new pushes to the branch
  push:

      

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  id-token: write
  packages: write

jobs:
  deployment:
    runs-on: ubuntu-latest
  
    steps:
    # Checkout your projects repository based on the ref provided by the branch-deploy step
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # use github cli to get changed files on current branch
    - name: Get changed files
      id: changed-files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        changed=$(gh pr diff --name-only)
        echo "::set-output name=changed::$changed"
        echo $changed 
  
    # loop through each file name
    - name: Loop through each file name
      run: |
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
          echo "File name: $file"
        done
