# github action that just checks for the files changed in a PR
name: "test-changed-files"

on:
  workflow_dispatch:
  # run on new pushes to the branch
  push:

      

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  id-token: write
  packages: write

jobs:
  deployment:
    runs-on: ubuntu-latest
  
    steps:
    # Checkout your projects repository based on the ref provided by the branch-deploy step
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # use github cli to get changed files on current branch
    - name: Get files changing in the Pull Request
      id: changed-files
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr diff --name-only > changed-files.txt

    - name: Get changed files
      id: get-changed-files
      run: |
        for file in $(cat changed-files.txt); do
          echo "Changed file: $file"
        done
    
    - name: Check if changed files contain a specific file
      id: check-file
      run: |
        for file in $(cat changed-files.txt); do
          if [[ $file != "README.md" ]]; then
            echo "Full Production Deployment Required"
            echo "::set-output name=full-deploy::true"
            break
          fi
        done

    - name: Check if full deployment is required
      if: steps.check-file.outputs.full-deploy == 'true'
      run: |
        echo "Full Deployment Required"

    - name: Check if full deployment is not required
      if: steps.check-file.outputs.full-deploy != 'true'
      run: |
        echo "No Full Deployment Required"